# Generated by Django 4.2.1 on 2023-06-01 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25, verbose_name='ФИО')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extradition', models.IntegerField(verbose_name='Выдачи')),
                ('ti', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ТИ')),
                ('kis', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='КИС')),
                ('trener', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Тренер')),
                ('client', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Клиент')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Итого')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('fio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kpi.staff', verbose_name='ФИО')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Продажи',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-time_create', 'fio'],
            },
        ),
    ]
