# Generated by Django 4.2.1 on 2023-06-17 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kpi.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='client',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='extradition',
            field=models.IntegerField(blank=True, default=0, verbose_name='Выдачи'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='fio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kpi.staff', verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='kis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='КИС'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='ti',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='ТИ'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='trener',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, upload_to=kpi.models.get_upload_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
